solon.app:
  name: myCharServ

chatServ:
  chatServerName: myCharServ
  port: 10010
  vertx:
    eventLoopPoolSize: 50
  deploy:
    instances: 20
  redis:
    endpoints:
      - "redis://localhost:7777"


# solon log
solon.logging.appender:
  console:
    level: info
    pattern: "%highlight(%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} [-%t][*%X{traceId}]%tags%boldMagenta([%logger{20}]) =>) %msg%n"
  file:
    name: "logs/${solon.app.name}"
    level: INFO
    pattern: "%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} [-%t][*%X{traceId}]%tags[%logger{20}]: %n%msg%n"

# 记录器级别的配置示例
solon.logging.logger:
  "io.netty.*":
    level: debug